name: Build and Package
on: [push, pull_request]

env:
  GO_REPO: gameontext/gameon-auth
  SUBMODULE: auth
  JAVA_VERSION: 11
  JAVA_DISTRO: temurin

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      submodule: ${{ env.SUBMODULE }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRO }}
        cache: gradle

    - name: Build with Gradle
      id: gradle-build
      run: ./gradlew build

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.GO_REPO }}
        tags: |
          type=schedule,pattern={{date 'YYYYMMDD'}}
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,enable=true,priority=200,prefix=,suffix=,value=gh-${{ github.ref_name }}-${{ github.run_number }}

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.repository == ${{ env.GO_REPO }}
      uses: docker/build-push-action@v3
      with:
        context: ./auth-wlpcfg
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  call-submodule-update:
    needs: build
    uses: gameontext/gameon/.github/workflows/updateSubmodule.yml@main
    with:
      submodule: ${{ needs.build.outputs.submodule }}
      submodule_ref: ${{ github.sha }}
      target_branch: ${{ github.ref_name }}
    secrets: inherit
